### ISSUE TITLE
Unable to use API, java.lang.NoClassDefFoundError: world/bentobox/aoneblock/AOneBlock

### ISSUE THREAD

**Issue by Rixafy** [BentoBoxWorld/AOneBlock#161] opened 2021-04-18 15:13 UTC
Hi, I'm trying to use API to get island phase etc. I want to acces AOneBlock class, so I tried

```kotlin
private lateinit var aOneBlock: AOneBlock

init {
    val optional = BentoBox.getInstance().addonsManager.getAddonByName<AOneBlock>("AOneBlock")
    if (optional.isPresent) {
        aOneBlock = optional.get()
    }
}
```

(I have imported `world.bentobox.aoneblock.AOneBlock`)

but I get an error

```
[16:59:05] [Server thread/ERROR]: Exception details below: 
java.lang.NoClassDefFoundError: world/bentobox/aoneblock/AOneBlock
	at net.minecord.cordex.server.oneblock.OneBlockController.<init>(OneBlockController.kt:28) ~[?:?]
```

error is at line where I use `AOneBlock` class, I also tried

```kotlin
for (addon in BentoBox.getInstance().addonsManager.addons) {
    Bukkit.broadcastMessage(addon.javaClass.name)
    if (addon is AOneBlock) {
        aOneBlock = addon
    }
}
```

and it broadcasts a message 
![image](https://user-images.githubusercontent.com/45132928/115150483-e3927000-a068-11eb-990f-c56ef0131c11.png)
and then I got the same error again when I try to cast it to AOneBlock class

I have plugin BentoBox as a dependency, and I tried it also later by reloading my plugin so I ensure all server classes are loaded, but then same error happened again.

### Environment

![image](https://user-images.githubusercontent.com/45132928/115150553-29e7cf00-a069-11eb-985a-d3170005ccd2.png)```
_______
```

**Comment by BONNe** [comment] 2021-04-18 18:07
Due to the Java ClassLoader hierarchy, only BentoBox addons can directly access other addons.

Plugins can use AddonRequestHandler for accessing some data.

https://docs.bentobox.world/en/latest/BentoBox/Request-Handler-API---How-plugins-can-get-data-from-addons/

AOneBlock requests are not in doc (@tastybento), however, there are 2 request handlers:

1) island-stats: https://github.com/BentoBoxWorld/AOneBlock/blob/develop/src/main/java/world/bentobox/aoneblock/requests/IslandStatsHandler.java
2) location-stats: https://github.com/BentoBoxWorld/AOneBlock/blob/develop/src/main/java/world/bentobox/aoneblock/requests/LocationStatsHandler.java

**Comment by Rixafy** [comment] 2021-04-18 18:40
Thanks, btw just a detail, in the docs there is called AddonRequestBuilder as a static class, it's required to create new instance and then call methods.

**Comment by BONNe** [comment] 2021-04-18 18:44
Well, builder is a wrapper around the handler.

**Comment by Rixafy** [comment] 2021-04-18 19:06
Yes, but in the docs it's `AddonRequestBuilder.method()` instead of `(new AddonRequestBuilder()).method()` but maybe it's intended.

**Comment by Rixafy** [comment] 2021-04-19 00:52
Btw, I also have the same problem with events
```
[Cordex] Plugin Minecordv0.0.1 has failed to register events for class net.minecord.cordex.stats.oneblock.StatsOneBlockListener because world/bentobox/level/events/IslandLevelCalculatedEvent does not exist.
```
(and it's same for AOneBlock event, I have plugin as softpend, so my plugin loads after Bentobox)

**Comment by tastybento** [comment] 2021-04-19 03:25
If you are writing a plugin, you can only "see" other plugins, and not classes plugins load dynamically. Therefore, you need to register for BentoBox events, not Addon events. So, register to listen for BentoBoxEvent, which is what IslandLecvelCalculatedEvent extends. Then to get data out of that event, you will need to use BentoBoxEvent#getKeyValues().

BONNe put a useful example in his Likes documentation:

```
@EventHandler(priority = EventPriority.MONITOR)
public void onLike(BentoBoxEvent event) {
    if (event.getEventName().equals("LikeAddEvent")) {
        UUID user = (UUID) event.getKeyValues().get("user");
        String islandId = (String) event.getKeyValues().get("islandId");
    }
}
```

**Comment by Rixafy** [comment] 2021-04-19 11:22
Thanks @tastybento, I tried it but I can't catch MagicBlockEvent or MagicBlockEntityEvent, both code blocks are called when `IslandPreLevelEvent` and `IslandLevelCalculateEvent` are called, but when I break the magic block, nothing happened, I also I couldn't catch MagicBlockEntityEvent in that broadcast message. I tried also to separate events to 2 classes but same result, like those events weren't even called o.O.

![image](https://user-images.githubusercontent.com/45132928/115228229-ccf42380-a111-11eb-9807-3dba0318f850.png)

**Comment by tastybento** [comment] 2021-04-19 14:31
Did you register the listener with Bukkit?

**Comment by Rixafy** [comment] 2021-04-19 14:32
Yes, because events like IslandEnterEvent, IslandLevelCalculateEvent etc. are calling those methods.

**Comment by Rixafy** [comment] 2021-04-19 18:34
I had 1.5.5 snapshot, so I downgraded to 1.5.4 but it isn't working, I'm just listening to BentoBoxEvent without any conditions with only 1 line for broadcast message, enter/leave/level event's are called, but when I break the oneblock magic block nothing happens, I tired also to change priorities of the events, create new listener and registering it, but nothing really helps, like those events weren't even called, any idea what could I try? @tastybento 

It seems to be related only to AOneBlock addon, because none of the events were fired, I tried also complete a phase, but events from Level plugin are called, for instance IslandLevelCalculateEvent or IslandPreLevelEvent.

**Comment by tastybento** [comment] 2021-04-21 01:31
I don't understand why you wouldn't see it. 

It's definitely being called: https://github.com/BentoBoxWorld/AOneBlock/blob/35ff185eb14d597870bccf4a5df2b19f9bb44e57/src/main/java/world/bentobox/aoneblock/listeners/BlockListener.java#L483

And those events extend BentoBoxEvent:
https://github.com/BentoBoxWorld/AOneBlock/blob/35ff185eb14d597870bccf4a5df2b19f9bb44e57/src/main/java/world/bentobox/aoneblock/events/AbstractMagicBlockEvent.java#L17

I can't write a test plugin now to verify, but I can't see anything in the code that would indicate it shouldn't be being called. Do you?

**Comment by Rixafy** [comment] 2021-04-21 13:16
No, I checked the code but I didn't find anything suspicious, I'll try to catch the event in another plugin.

**Comment by Rixafy** [comment] 2021-04-21 13:48
@tastybento I created test plugin if you want to try it, https://github.com/Rixafy/BentoBoxEventTestPlugin it's already built in build/libs so you can download and try it, it can be build with `gradlew build` command.

**Comment by tastybento** [comment] 2021-04-22 02:34
Thanks. I'm busy right now but I should be able to try out things at the end of the week and weekend.

**Comment by Rixafy** [comment] 2021-04-22 02:50
No problem, I already fixed it in that PR, so it's working but I'm not sure why are handler methods in BentoBoxEvent deprecated.

**Comment by BONNe** [comment] 2021-04-22 06:51
Your fix is incorrect. Each event should have their own handlers.

**Comment by Rixafy** [comment] 2021-04-22 12:36
What should I change? Since I can't use any class from the addon, and if you want to catch BentoBoxEvent, handlers should be shared if I want to listen for BentoBoxEvent and check the event name.

**Comment by tastybento** [comment] 2021-04-22 14:32
I can confirm that AOneBlock isn't firing events. I'm looking into why. Noted on the PR and handlers.

**Comment by tastybento** [comment] 2021-04-22 14:50
Well, I found the problem and it's again a case of plugins vs addons and Java class loaders. In order to be able to listen for BentoBoxEvent, the handler system **must** be in BentoBoxEvent class. Currently, they are but deprecated because by doing that, every event that extends that class will be only and ever a BentoBoxEvent. However, this also prevents Addons from listening only for MagicBlockEvent. Addons will fire for every single BentoBoxBox event even if they are only trying to listen to MagicBlockEvent. So in summary, having each event have its own handlers is the right thing to do for addons, but it means plugins cannot listen for them.

So, the only way to fix this I can see is to fire two different events at the same time. One event will be for plugins to listen to that will have a global handler and one will be for addons with the same information. 

By the way, the only reason Level works is because it doesn't implement its own handlers.

I'll need to think of how to fix this and I'm open to suggestions.

**Comment by BONNe** [comment] 2021-04-22 15:00
Well, so we returned to the AddonEvent class.

Addon Events should extend AddonEvent class instead of BentoBoxEvent.
AddonEvents should contain its handler that will be used for plugins. Addon events will not have their own handlers, as most events are used by the plugins.

That is my thought. 

Calling 2 events is also a solution, but will you not end up with double events? One from Main Class and one from BentoBoxEvent class?

**Comment by tastybento** [comment] 2021-04-22 15:06
BentoBox could echo addon events perhaps. It could listen for all BentoBoxEvents itself and then fire a sympathetic event that would contain the same key/values and name of the internal event. This would be for plugin consumption.

**Comment by Rixafy** [comment] 2021-04-22 15:08
Did you consider making addons like real bukkit plugins? Because it would solve a lot of pain for other developers, and it wouldn't event be a BC break, because you can just add Plugin.java to addon where would be onEnable() method for bukkit, and when BentoBox starts it checks if there is Plugin.java and if yes, it would move the addon to /plugins folder and server would be restarted.

**Comment by tastybento** [comment] 2021-04-22 19:37
Yeah, I've been thinking the same thing. I'll have to think through the implications.

**Comment by tastybento** [comment] 2021-07-06 20:50
>Did you consider making addons like real bukkit plugins? 

This is now done with Pladdons in 1.17.0 BentoBox.

**Closed** 2021-07-06 20:50 UTC
Labels: bug, under investigation
