### ISSUE TITLE
Commands rewards on phase complete

### ISSUE THREAD

**Issue by abhisantos** [BentoBoxWorld/AOneBlock#130] opened 2020-11-18 22:09 UTC
#### Is your feature request related to a problem?

Not related to a problem.

#### Describe the solution you'd like us to implement.

Add the possibility for admin to add commands as rewards on phase completion. For example, when a player completes a phase, the console runs a command specified in config like ''give player diamond'' or ''tell player bla bla''. 
Being able to add multiple commands would be nice too!
Thank you

**Comment by fredthedoggy** [comment] 2020-11-18 22:17
This is a duplicate of #108

**Closed** 2020-11-19 00:15 UTC
Labels: duplicate
