### ISSUE TITLE
[URGENT] The oneblock's absolutely yeets blocks for no reason when a mob spawns.

### ISSUE THREAD

**Issue by ClickErrorxD** [BentoBoxWorld/AOneBlock#267] opened 2022-07-05 23:20 UTC
### Expected behavior

It's obvious once you review our video's recorded.

The plugin shouldn't break blocks that aren't touching a mob's hitbox, whatsoever. (The cow video below....)

BentoBox shouldn't effect blocks this badly. It limits player's being able to place/do things on their island when it's near the oneblock.

### Observed/Actual behavior

Even if the mob's hitbox that is used is smaller than the the height of the block around the oneblock, the plugin breaks it. We tested this on a fresh server with limited plugins as well.

### Steps/models to reproduce

Place a block 2 blocks or less/more around the oneblock. When a mob spawns after mining your oneblock, it'll delete it.
 As videos below show, this breaks many many plugins that offer place-able items. Such as hoppers, beacons.

### BentoBox version

![image](https://user-images.githubusercontent.com/87890013/177432395-5bc9bda4-dcf9-438f-9dfa-6e555cf3d6d4.png)

### Plugin list

Plugins (78): Bentobox, Essentials, KGenerators, UpgradeableHoppers, Vault

### Other

The proof of the plugin can be blatantly viewed with the clips we provided in their discord for support. One of the contributors swears up and down that this isn't even an issue or bug, yet you can see how it'll effect many different plugins.

https://youtu.be/tKQYKXRHZ_8 - Breaks vanilla blocks and drops it.

https://youtu.be/aaQkYZw8XEo - Breaks another plugin's item by dropping a default vanilla hopper, despite the hopper having full maxed upgrades before Bentobox breaks it. [[Upgradeable Hoppers](https://www.spigotmc.org/resources/upgradeable-hoppers-fast-hopper-plugin-link-containers-item-transfer-suction-chunk-1-19-support.69201/)]

https://youtu.be/fxnGGR8RwRk -[[Generators](https://www.spigotmc.org/resources/kgenerators-custom-items-blocks-entities-generators-spawners-stone-item-generator-1-8-1-18.79246/updates)]

Hoping this get's fixed as soon as possible. Oneblock nation, my server, released 5/2/22 and we've already had 7+, close to 10 at this point, different reports by player's. Until a fix is made, we used message's from bentobox's language file to tell users not to place valuable blocks around the oneblock... however, this just isn't and won't ever be enough.

**Comment by tastybento** [comment] 2022-07-16 17:53
I can tell you feel very passionate about this but it's by design and not a bug. Without this, it would be possible to build around the magic block and cause suffocation of mobs and therefore bypass any difficulty with them spawning. Players can learn that this happens and avoid the magic block area. I'll close this one and keep the request open for #268.

**Closed by tastybento** 2022-07-16 17:53 UTC

**Comment by ClickErrorxD** [comment] 2022-07-16 18:27
> I can tell you feel very passionate about this but it's by design and not a bug. Without this, it would be possible to build around the magic block and cause suffocation of mobs and therefore bypass any difficulty with them spawning. Players can learn that this happens and avoid the magic block area. I'll close this one and keep the request open for #268.

Appreciated!
