### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by ImFx-MC** [BentoBoxWorld/AOneBlock#86] opened 2020-06-11 16:05 UTC
Hi, When I put BentoBox on my server with OneBlock addon, BlockBreakEvent does not work for me.

Here is error: https://hastebin.com/nobomidavo.pl

BentoBox and Server version output:
https://hastebin.com/manehuluci.css

Thanks for support.

**Comment by tastybento** [comment] 2020-06-11 21:48
This is a duplicate of #85. Can you try the latest version of Paper Spigot and tell me if you still get the error: https://papermc.io/downloads ?

Where and when did you get your version of Spigot?

**Comment by tastybento** [comment] 2020-06-12 02:54
Update your server and it will work.

**Closed by tastybento** 2020-06-12 02:54 UTC
Labels: duplicate, under investigation
