### ISSUE TITLE
[Bug?] Blocks drop in void and sometimes in my inventory

### ISSUE THREAD

**Issue by maxlehot1234** [BentoBoxWorld/AOneBlock#12] opened 2020-04-27 13:14 UTC
#### Describe the bug

Blocks break from the infinite block drops in the void and not in my inventory all the time.

#### Steps to reproduce the behavior

Install the plugin and break the infinite block

#### Expected behavior

Blocks should go in my inventory and not dropping in the void

##### BentoBox Version (Mandatory)

```
[09:13:14 INFO]: Running PAPER 1.15.2.
[09:13:14 INFO]: BentoBox version: 1.12.0
[09:13:14 INFO]: Database: JSON
[09:13:14 INFO]: Loaded Game Worlds:
[09:13:14 INFO]: oneblock_world (OneBlock): Overworld, Nether*
[09:13:14 INFO]: Loaded Addons:
[09:13:14 INFO]: AOneBlock 1.1.5 (ENABLED)
[09:13:14 INFO]: Border 1.0.7 (DISABLED)
[09:13:14 INFO]: Chat 1.0.5 (ENABLED)
[09:13:14 INFO]: Level 1.9.3 (ENABLED)
[09:13:14 INFO]: Limits 1.9.4 (ENABLED)
[09:13:14 INFO]: Warps 1.9.3 (ENABLED)
```

#### Plugins (Optional)

```
Plugins (5): BentoBox, CMI, Essentials, EssentialsSpawn, Multiverse-Core
```
 

I just want to know if its just me or if I can fix it myself or if a plugin update will be required.

Thanks again for your help and have a nice day/night

**Comment by tastybento** [comment] 2020-04-27 14:37
It's part of the game! Blocks break naturally and so can fling out in any direction. Have a look at some of my videos: https://www.youtube.com/playlist?list=PL1A9KkdJphyr332zRzRxziJ1uoOyEYj2s

**Comment by maxlehot1234** [comment] 2020-04-27 15:00
@tastybento The OneBlock map will make blocks drops on the infinite block instead of droping in the void.

Is it something possible to do with a true/false option?

**Comment by maxlehot1234** [comment] 2020-04-27 19:34
Maybe develop a drop2inv addon ;) It can be useful for all gamemodes for bentobox (maybe allow use to a list of gamemodes in the config file will do the trick)

**Comment by maxlehot1234** [comment] 2020-04-27 20:56
@tastybento Found the plugin that do the trick in the meantime:
https://github.com/ThePhilderbeast/AutoPickup

Works like a charm :)

**Comment by maxlehot1234** [comment] 2020-04-30 02:31
This ticket can be closed. If anyone want a really fix, they Can use [vkautopickup ](https://www.mc-market.org/resources/14044/)

**Comment by tastybento** [comment] 2020-05-02 03:15
Duplicate of #38. I'll keep that one open and close this one.

**Closed by tastybento** 2020-05-02 03:15 UTC
Labels: enhancement, not a bug
